export const SETDISPLAYSPINNER = 'SETDISPLAYSPINNER'
export const SETHEADERHEIGHT = 'SETHEADERHEIGHT'
export const SETISACTIVEHAMBURGERBUTTON = 'ISACTIVEHAMBURGERBUTTON'
export const SETITEMSNAV = 'SETITEMSNAV'